### PR TITLE
Check non-utf8 output instead of panicking

### LINKED ISSUE #14: Cannot handle non-utf8 in stderr/stdout
Attempting to do this causes something in compiletest to crash.

```
     Running tests/compiletest.rs (target/debug/deps/compiletest-5625b9d9b19cedc6)
## Running ui tests in tests/pass against miri for x86_64-unknown-linux-gnu
   Compiler flags: ["--error-format=json", "--edition", "2018", "-Dwarnings", "-Dunused", "-Zui-testing", "--target", "x86_64-unknown-linux-gnu"]
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 31, error_len: Some(1) }
Location: /home/cbiffle/.cargo/registry/src/github.com-1ecc6299db9ec823/ui_test-0.3.1/src/lib.rs:467
```

This is because the test framework does this (`ui_test/src/lib.rs` line 466):

```rust
    let diagnostics = rustc_stderr::process(path, stderr);
    let stdout = std::str::from_utf8(stdout).unwrap();  // <-- not good
```

So, evidently, tests are forbidden from printing anything in non-UTF-8. Miri, however, handles it fine, as attested by being able to `./miri run` that same test case.

_Originally posted by @cbiffle in https://github.com/rust-lang/miri/issues/2606#issuecomment-1284826843_

### PR DESCRIPTION
**Pull request by oli-obk**
Alternative to https://github.com/oli-obk/ui_test/pull/21

fixes #14

### CODE REVIEW

File: src/diff.rs [hunk 1]
```diff
@@ -152,10 +154,19 @@ impl<'a> DiffState<'a> {
...
+    if let (Ok(expected), Ok(actual)) = (std::str::from_utf8(expected), std::str::from_utf8(actual))
+    {
+        let mut state = DiffState::default();
+        for row in lines(expected, actual) {
+            state.row(row);
+        }
+        state.finish();
+    } else {
+        eprint!("{}", "-".red());
+        std::io::stderr().write(expected).unwrap();
```
Comment (RalfJung) [inline src/diff.rs:167]: This will print many lines, right? That would look rather strange I think.
```
-the_output
some non-utf-8
+the_output
other non-utf-8
```
Maybe it should just do the diff on the utf-8-lossy result but print a warning saying the diff might miss some information?

File: src/lib.rs [hunk 2]
```diff
@@ -164,7 +173,10 @@ pub fn run_tests(mut config: Config) -> Result<()> {
 pub fn run_file(mut config: Config, path: &Path) -> Result<std::process::ExitStatus> {
     config.build_dependencies_and_link_them()?;
 
-    let comments = Comments::default();
+    let comments = match std::fs::read_to_string(path) {
+        Ok(content) => Comments::parse(path, &content)?,
+        Err(_) => Comments::default(),
```
Comment (RalfJung) [inline src/lib.rs:178]: This seems bad, if there is a single non-utf8-character we just entirely ignore all comments in that file?

File: src/rustc_stderr.rs [hunk 3]
```diff
@@ -125,20 +122,16 @@ pub(crate) fn filter_annotations_from_rendered(rendered: &str) -> std::borrow::C
...
 pub(crate) fn process(file: &Path, stderr: &[u8]) -> Diagnostics {
-    let stderr = std::str::from_utf8(stderr).unwrap();
-    let mut rendered = String::new();
+    let mut rendered = Vec::new();
     let mut messages = vec![];
     let mut messages_from_unknown_file_or_line = vec![];
-    for line in stderr.lines() {
-        if line.starts_with('{') {
-            match serde_json::from_str::<RustcMessage>(line) {
+    for (line_number, line) in stderr.split_inclusive(|&c| c == b'\n').enumerate() {
```
Comment (RalfJung) [inline src/rustc_stderr.rs:128]: `&[u8]` implements `BufRead` which has a `lines` method, can't we use that?

Comment (oli-obk) [reply src/rustc_stderr.rs:128]: because that produces `String`s again

Comment (RalfJung) [reply src/rustc_stderr.rs:128]: Ah, bummer.

This is not entirely identical though, `lines()` also has handling for `\r`.

File: src/lib.rs (hunk 2 above)
Comment (oli-obk) [reply src/lib.rs]: I've decided to just error if a special comment has non-utf8 before the end of line

File: src/rustc_stderr.rs (hunk 3 above)
Comment (oli-obk) [reply src/rustc_stderr.rs]: I switched to bstr's `lines()` function which works correctly

File: src/diff.rs [hunk 4]
```diff
@@ -152,9 +152,19 @@ impl<'a> DiffState<'a> {
...
 
-pub fn print_diff(expected: &str, actual: &str) {
+pub fn print_diff(expected: &[u8], actual: &[u8]) {
+    let expected_str = String::from_utf8_lossy(expected);
+    let actual_str = String::from_utf8_lossy(actual);
+
+    if expected_str.as_bytes() != expected || actual_str.as_bytes() != actual {
+        eprintln!(
+            "{}",
+            "Non-UTF8 characters in output, diff may be imprecise around the Non-UTF8 chars".red()
```
Comment (RalfJung) [inline src/diff.rs:162]:
```suggestion
            "Non-UTF8 characters in output, diff may be imprecise.".red()
```

**Comment by RalfJung** [comment]
Yes, I like this. :-)
